// The browser and the firmware each derive a speech phrase's filename by
// hashing the phrase. If those two implementations ever disagree the failure is
// SILENT: the device looks for files the browser never uploaded and you simply
// get no speech, with nothing in any log to explain it.
//
// So these expected values are not "whatever the JS happens to produce" — they
// were generated by compiling and running the EXACT fnv1a32() in
// main/speech_player.c. If this test fails, the two have diverged; fix the one
// that changed rather than updating the constants.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { fnv1a32, speechFilename } from '../src/js/gen/sdsync.js';

// voice, text, filename-from-C
const VECTORS = [
    ['default', 'Hello world',                       'speech/sp_456bd5be.wav'],
    ['en-US',   'Beginning at ten hertz, in alpha.', 'speech/sp_7a1c2480.wav'],
    ['',        'Let your breath slow.',             'speech/sp_2f65c389.wav'],
    ['default', '',                                  'speech/sp_68714006.wav'],
    ['default', '"quoted" and #hash',                'speech/sp_e8719bbe.wav'],
];

test('speechFilename matches the firmware byte for byte', () => {
    for (const [voice, text, expected] of VECTORS) {
        assert.equal(speechFilename(voice, text), expected,
            `voice=${JSON.stringify(voice)} text=${JSON.stringify(text)}`);
    }
});

test('an empty or "default" voice normalises the same way both sides do', () => {
    // speech_player.c: (voice && *voice) ? voice : "default"
    const a = speechFilename('', 'x');
    const b = speechFilename('default', 'x');
    const c = speechFilename(null, 'x');
    const d = speechFilename('   ', 'x');
    assert.equal(a, b);
    assert.equal(b, c);
    assert.equal(c, d);
});

test('fnv1a32 stays in 32-bit unsigned space', () => {
    // A plain `*` instead of Math.imul silently loses precision past 2^53 and
    // would drift from C only for some inputs — which is the worst kind of bug.
    for (const s of ['', 'a', 'The quick brown fox jumps over the lazy dog'.repeat(8)]) {
        const h = fnv1a32(s);
        assert.ok(Number.isInteger(h), 'integer');
        assert.ok(h >= 0 && h <= 0xffffffff, `in range: ${h}`);
    }
    assert.equal(fnv1a32(''), 0x811c9dc5, 'empty string is the FNV offset basis');
});

test('different phrases and voices give different files', () => {
    const seen = new Set();
    for (const [v, t] of [['default', 'one'], ['default', 'two'], ['en-US', 'one']]) {
        const f = speechFilename(v, t);
        assert.ok(!seen.has(f), 'no collision for ' + f);
        seen.add(f);
    }
});
